apiVersion: apps/v1
kind: Deployment
metadata:
  name: vic-deploy
spec:
  selector:
    matchLabels:
      app: engr
  replicas: 5
  template:
    metadata:
      labels:
        app: engr
    spec:
      containers:
      - name: vic-container
        image: rudolphnfor/etechapp
        ports:
        - containerPort: 8080


